### ISSUE TITLE
ErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to ...

### ISSUE THREAD

**Issue by lenybernard** [Victoire/WidgetFormBundle#30]
```
ErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Victoire\Widget\FormBundle\Event\WidgetFormeMailEvent::__construct() must be of the type array, null given, called in /var/www/troopers.agency/releases/20171003154453/vendor/victoire/form-widget/Victoire/Widget/FormBundle/Controller/FormController.php on line 105 in /var/www/troopers.agency/releases/20171003154453/vendor/victoire/form-widget/Victoire/Widget/FormBundle/Event/WidgetFormeMailEvent.php:16
Stack trace:
#0 /var/www/troopers.agency/releases/20171003154453/vendor/victoire/form-widget/Victoire/Widget/FormBundle/Controller/FormController.php(105): Victoire\Widget\FormBundle\Event\WidgetFormeMailEvent->__construct(NULL)
#1 [internal function]: Victoire\Widget\FormBundle\Controller\FormController->addFormAnswerAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/troopers.agency/releases/20171003154453/var/cache/classes.php(4672): call_user_func_array(Array, Array)
#3 /var/www/troopers.agency/r
  File "vendor/victoire/form-widget/Victoire/Widget/FormBundle/Event/WidgetFormeMailEvent.php", line 16, in handleFatalError
    public function __construct(array $data)
  File "[Anonymous function]", line 0
    Raven_ErrorHandler->handleFatalError
```

**Comment by lenybernard** [comment]
https://github.com/Victoire/WidgetFormBundle/commit/ca7a314c376dfcca66d11a6e9d3dcce46c255b31
